name: End-to-End Tests

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      - name: react-app
        alias: react-app
        dockerfile: packages/app1/Dockerfile
      - name: nextjs-app
        alias: nextjs-app
        dockerfile: packages/app2/Dockerfile
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Start Containers
        working-directory: packages
        run: docker-compose up -d

      - name: Wait for Apps to Start
        run: sleep 30

      - name: Run WebDriver.io Tests
        working-directory: test
        run: docker build -t webdriverio-tests . && docker run --network container:nextjs-app --network container:react-app webdriverio-tests

      - name: Stop and Remove Containers
        run: docker-compose down
