name: End-to-End Tests

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Create network
      - name: Create Docker Network
        run: docker network create e2e-tests

      # Build Docker Images
      - name: Build React Docker Image
        working-directory: ${{ github.workspace }}/packages/app1
        run: |
          docker build -t react-app-image-name:latest .
      - name: Build Nextjs Docker Image
        working-directory: ${{ github.workspace }}/packages/app2
        run: |
          docker build -t nextjs-app-image-name:latest .

      # Run Docker Containers
      - name: Run React Docker Container
        run: |
          docker run -d -p 3000:3000 --name react-app --network e2e-tests react-app-image-name:latest
      - name: Run Next Docker Container
        run: |
          docker run -d -p 3334:3334 --name nextjs-app --network e2e-tests nextjs-app-image-name:latest

      # Run Tests
      - name: Wait for Apps to Start
        run: sleep 30

      - name: Install Dependencies
        working-directory: test
        run: | 
          yarn install
          yarn global add webdriverio

      - name: Run WebDriver.io Tests
        working-directory: test
        run: yarn test:local

      - name: Stop and Remove Containers
        run: |
          docker stop nextjs-app
          docker stop react-app
          docker rm nextjs-app
          docker rm react-app
