name: Deployment

on: workflow_dispatch

jobs:
  deployment1:
    environment:
      name: app1
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app1
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: app1/build # change to your build folder

  deployment2:
    environment:
      name: app2
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app2
    steps:
      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.0
        with:
          path: app2/build # change to your build folder