name: End-to-End Tests

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      react-app:
        image: react-app-image-name:latest
        ports:
          - 3000/tcp
        options:
          --name react-app
          --workdir /packages/app1

      nextjs-app:
        image: nextjs-app-image-name:latest
        ports:
          - 3000/tcp
        options:
          --name nextjs-app
          --workdir /packages/app2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Wait for Apps to Start
        run: sleep 30

      - name: Run WebDriver.io Tests
        working-directory: test
        run: |
          docker build -t webdriverio-tests
          docker run --network container:nextjs-app --network container:react-app webdriverio-tests

      - name: Stop and Remove Containers
        run: |
          docker stop nextjs-app
          docker stop react-app
